# Generated by Django 6.0.7 on 2026-07-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('class_arm', models.CharField(blank=True, max_length=50)),
                ('eligibility_status', models.CharField(choices=[('Eligible', 'Eligible'), ('Not Eligible Yet', 'Not Eligible Yet')], editable=False, max_length=20)),
                ('has_voted', models.BooleanField(default=False)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
