# Generated by Django 6.0.7 on 2026-07-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(default='Governor', max_length=50)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
